version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=promptsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - prompt-network

  redis:
    image: redis:7-alpine
    networks:
      - prompt-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/promptsdb
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - prompt-network

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    networks:
      - prompt-network

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    networks:
      - prompt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - prompt-network
    depends_on:
      - backend

networks:
  prompt-network:
    driver: bridge

volumes:
  postgres_data:
